server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_eastdemo?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #old driver class com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #  数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validaionQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
# mybatis
mybatis:
  config-locations:
    classpath: mybatis/mybatis-config.xml
  mapper-locations:
    classpath: mysql-mapper/*.xml
  type-aliases-package: com.shptchangfeng.eastdemo.dao

# druid
druid:
  # 所有连接相关的日志
  connectionLogEnabled: false
  # 所有Statement相关的日志
  statementLogEnabled: false
  # 是否显示结果集
  resultSetLogEnabled: false
  # 是否显示SQL语句
  statementExecutableSqlLogEnable: true

